version: "2"
checks:
  similar-code:
    enabled: false
plugins: 
  eslint:
    enabled: true
    channel: "eslint-6"
exclude_patterns:
  "tests/"
  "spec/"
  "**/*.spec.js"
  "**/*.spec.jsx"
  "**/*.spec.ts"
  "**/*.spec.tsx"
  "**/vendor/"
  "**/node_modules/"